/*
 * This source file was generated by the Gradle 'init' task
 */
package week.mlbb;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ItemMechanism.ItemNode root = ItemTrees.buildRecipeTree();
        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.print("Search Item Recipe: ");
            String input = scanner.nextLine();
            if (input.equalsIgnoreCase("exit")) {
                break;
            }
            ItemMechanism.ItemNode targetNode = ItemMechanism.findNode(root, input);
            if (targetNode != null) {
                System.out.println("--- Recipe for " + targetNode.name + " ---");
                ItemMechanism.printTree(targetNode, 0);
            } else {
                System.out.println("Item not found in the build tree.");
            }
            System.out.println("Paths to " + input + ":");
            ItemMechanism.printPathsToEndItem(root, input, new ArrayList<>());

            ItemMechanism.ItemNode itemNode = ItemMechanism.findNode(root, input);
            if (itemNode != null) {
                System.out.println(input + " Branch Height: " + ItemMechanism.height(itemNode)); 
            }

            System.out.println("Continue searching? (Type Y to continue, any other key to exit)");
            String continueSearch = scanner.nextLine();
            if (!continueSearch.equalsIgnoreCase("Y")) {
                break;
            }
        }
        scanner.close();
    }
}